export const siteConfig = {
  company: "Hürland-Scuric Immobilien GmbH",
  shortName: "Hürland Hausverwaltung",
  tagline: "Ihre Hausverwaltung mit individuellem und persönlichem Service",
  headline: "Zuverlässige Hausverwaltung in Dorsten & Umgebung",
  city: "Dorsten",
  address: {
    street: "Ostwall 40-42",
    zip: "46282",
    city: "Dorsten",
  },
  phone: "02362/9930550",
  phoneLink: "+4923629930550",
  mobile: "0163/5104073",
  mobileLink: "+491635104073",
  fax: "02362/9930551",
  email: "info@huerland-hausverwaltung.de",
  hours: "Mo.–Fr. 9:00 – 12:00 Uhr",
  usp: "Faire Konditionen, Kompetenz und Professionalität",
  values: ["Kundennähe", "Kompetenz", "Flexibilität", "Transparenz"],
  founded: "Hürland-Scuric Immobilien GmbH",
  managingDirector: "Birgit Hürland",
  registerCourt: "Amtsgericht Gelsenkirchen HRB 11990",
  taxId: "359/5762/4227",
  supervisoryAuthority: "Stadt Recklinghausen / Ordnungsamt",
  certification: "Zertifizierte Verwalterin nach §26a WEG",
  experienceYears: "15+",
  regions: [
    "Dorsten",
    "Marl",
    "Recklinghausen",
    "Bottrop",
    "Schermbeck",
    "Gladbeck",
  ],
};

export const nav = [
  { label: "Startseite", href: "/" },
  { label: "Mietverwaltung", href: "/mietverwaltung" },
  { label: "WEG-Verwaltung", href: "/weg-verwaltung" },
  { label: "Profil", href: "/profil" },
  { label: "Termin", href: "/termin" },
  { label: "Kontakt", href: "/kontakt" },
];
